TARGET_LEAGUES = [
    {
        "internal_league_key": "bra_serie_a",
        "display_name": "Brasileirao Serie A",
        "country": "Brazil",
        "priority": "P0",
        "provider_name": "api_football",
        "api_football_league_id": None,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P0 South America. API-Football coverage lists Brazil Serie A; exact id must be validated.",
        "api_football_search_terms": ["Serie A", "Brazil"],
    },
    {
        "internal_league_key": "argentina_primera",
        "display_name": "Argentina Primera Division",
        "country": "Argentina",
        "priority": "P0",
        "provider_name": "api_football",
        "api_football_league_id": None,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P0 South America. API-Football coverage lists Liga Profesional Argentina.",
        "api_football_search_terms": ["Liga Profesional Argentina", "Argentina"],
    },
    {
        "internal_league_key": "premier_league",
        "display_name": "Premier League",
        "country": "England",
        "priority": "P0",
        "provider_name": "api_football",
        "api_football_league_id": 39,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P0 Europe. Common API-Football id is 39; validate current player stats.",
        "api_football_search_terms": ["Premier League", "England"],
    },
    {
        "internal_league_key": "la_liga",
        "display_name": "La Liga",
        "country": "Spain",
        "priority": "P0",
        "provider_name": "api_football",
        "api_football_league_id": 140,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P0 Europe. Common API-Football id is 140; validate current player stats.",
        "api_football_search_terms": ["La Liga", "Spain"],
    },
    {
        "internal_league_key": "bundesliga",
        "display_name": "Bundesliga",
        "country": "Germany",
        "priority": "P0",
        "provider_name": "api_football",
        "api_football_league_id": 78,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P0 Europe. Common API-Football id is 78; validate current player stats.",
        "api_football_search_terms": ["Bundesliga", "Germany"],
    },
    {
        "internal_league_key": "serie_a_italy",
        "display_name": "Serie A Italy",
        "country": "Italy",
        "priority": "P0",
        "provider_name": "api_football",
        "api_football_league_id": 135,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P0 Europe. Common API-Football id is 135; validate current player stats.",
        "api_football_search_terms": ["Serie A", "Italy"],
    },
    {
        "internal_league_key": "ligue_1",
        "display_name": "Ligue 1",
        "country": "France",
        "priority": "P0",
        "provider_name": "api_football",
        "api_football_league_id": 61,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P0 Europe. Common API-Football id is 61; validate current player stats.",
        "api_football_search_terms": ["Ligue 1", "France"],
    },
    {
        "internal_league_key": "eredivisie",
        "display_name": "Eredivisie",
        "country": "Netherlands",
        "priority": "P1",
        "provider_name": "api_football",
        "api_football_league_id": None,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P1. Validate quickly after P0.",
        "api_football_search_terms": ["Eredivisie", "Netherlands"],
    },
    {
        "internal_league_key": "liga_portugal",
        "display_name": "Liga Portugal",
        "country": "Portugal",
        "priority": "P1",
        "provider_name": "api_football",
        "api_football_league_id": None,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P1. May appear as Primeira Liga or Liga Portugal.",
        "api_football_search_terms": ["Primeira Liga", "Portugal"],
    },
    {
        "internal_league_key": "colombia_primera_a",
        "display_name": "Colombia Categoria Primera A",
        "country": "Colombia",
        "priority": "P2",
        "provider_name": "api_football",
        "api_football_league_id": None,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P2. Keep mapped but do not show active until real player data is validated.",
        "api_football_search_terms": ["Primera A", "Colombia"],
    },
    {
        "internal_league_key": "uruguay_primera",
        "display_name": "Uruguay Primera Division",
        "country": "Uruguay",
        "priority": "P2",
        "provider_name": "api_football",
        "api_football_league_id": None,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P2. API-Football may split Apertura and Clausura.",
        "api_football_search_terms": ["Primera Division", "Uruguay"],
    },
    {
        "internal_league_key": "chile_primera",
        "display_name": "Chile Primera Division",
        "country": "Chile",
        "priority": "P2",
        "provider_name": "api_football",
        "api_football_league_id": None,
        "sportmonks_league_id": None,
        "status": "needs_validation",
        "notes": "P2. Keep mapped but do not show active until real player data is validated.",
        "api_football_search_terms": ["Primera Division", "Chile"],
    },
]


def get_target_leagues() -> list[dict]:
    return TARGET_LEAGUES


def get_active_leagues() -> list[dict]:
    return [league for league in TARGET_LEAGUES if league["status"] == "active"]

